"""
Smart Wish AI - Text Generation Service (Production Grade)

This module implements a serverless inference worker using Modal. It encapsulates
the Google Gemma-4B model to provide structured greeting card variations.

Architectural Design:
1.  **Serverless Scaling**: Utilizes Modal's GPU-accelerated workers (L4) for on-demand inference.
2.  **Structural Integrity**: Implements a 'defense-in-depth' strategy for JSON reliability:
    - LLM Pre-filling: Starting the assistant response with '{' to force valid JSON starts.
    - Post-processing: Programmatic markdown and filler stripping.
    - Key Normalization: Heuristic mapping of model-generated keys to API-stable keys.
"""

import modal
import json
import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../prompts')))
from prompts import MESSAGE_VARIATION_PROMPT, RESTRICTION_ANCHOR, SANITIZATION_SYSTEM_PROMPT, IMAGE_SANITIZATION_SYSTEM_PROMPT

PROMPTS_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '../prompts/prompts.py'))

# Define the Modal application and its runtime environment.
app = modal.App("smart-wish-text-v2")

# Container image definition with optimized dependency layer.
image = (
    modal.Image.debian_slim(python_version="3.11")
    .pip_install(
        "transformers",
        "torch",
        "accelerate",
        "hf_transfer",
        "huggingface_hub",
        "fastapi[standard]"
    )
    .env({
        "HF_HUB_ENABLE_HF_TRANSFER": "1",
        "HF_HOME": "/cache"
    })
    .add_local_file(PROMPTS_PATH, remote_path="/root/prompts.py")
)

MODEL_ID = "google/gemma-4-e4b-it"

# Volume used to cache model weights across container restarts to minimize cold-start latency.
model_cache = modal.Volume.from_name("model-cache", create_if_missing=True)

@app.cls(
    image=image,
    gpu="L4",
    secrets=[modal.Secret.from_name("huggingface-secret")],
    scaledown_window=300,
    volumes={"/cache": model_cache},
    startup_timeout=600,
)
class TextService:
    """
    Worker class for LLM inference. Optimized for low-latency greeting generation.
    """

    @modal.enter()
    def load_model(self):
        """Bootstraps the model and tokenizer into VRAM.
        
        This method is executed exactly once per container lifecycle. 
        It initializes the Hugging Face tokenizer and loads the Gemma-4B 
        model with bfloat16 precision to ensure optimal memory usage on the L4 GPU.
        """
        from transformers import AutoModelForCausalLM, AutoTokenizer
        import torch

        print(f"🚀 Booting Smart Wish Engine with {MODEL_ID}...")
        self.tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
        self.model = AutoModelForCausalLM.from_pretrained(
            MODEL_ID,
            dtype=torch.bfloat16,
            device_map="auto",
        )
        print("✅ Engine Ready.")

    def _strip_markdown(self, text: str) -> str:
        """Removes common markdown artifacts from the generated text.
        
        Acts as a programmatic safeguard against LLM hallucinations where the 
        model might include markdown formatting despite system prompt constraints.
        
        Args:
            text (str): The raw text generated by the model.
            
        Returns:
            str: The cleaned text stripped of common markdown symbols.
        """
        return text.replace("**", "").replace("__", "").replace("#", "").replace("`", "").strip()

    def _run_inference(self, messages: list, max_tokens: int, temp: float, top_p: float, add_gen_prompt: bool = True) -> str:
        """Executes the core inference loop for the language model.
        
        Applies the chat template to the input messages, runs generation in a 
        no-grad context for memory efficiency, and decodes the resulting tokens.
        
        Args:
            messages (list): A list of message dictionaries (role and content).
            max_tokens (int): The maximum number of new tokens to generate.
            temp (float): The temperature for sampling.
            top_p (float): The top_p (nucleus) sampling parameter.
            add_gen_prompt (bool, optional): Whether to append a generation prompt. Defaults to True.
            
        Returns:
            str: The generated text response.
        """
        import torch

        inputs = self.tokenizer.apply_chat_template(
            messages,
            add_generation_prompt=add_gen_prompt,
            return_tensors="pt",
            return_dict=True,
        ).to(self.model.device)

        with torch.no_grad():
            outputs = self.model.generate(
                inputs["input_ids"],
                attention_mask=inputs.get("attention_mask"),
                max_new_tokens=max_tokens,
                do_sample=True,
                temperature=temp,
                top_p=top_p,
                pad_token_id=self.tokenizer.eos_token_id
            )

        input_length = inputs["input_ids"].shape[1]
        return self.tokenizer.decode(
            outputs[0][input_length:],
            skip_special_tokens=True
        )

    def _generate_message(self, user_request: str, context: str = None) -> str:
        """Generates a single greeting card message based on user input.
        
        Constructs the conversational prompt using system instructions and the 
        user's request, optionally appending any additional context provided.
        
        Args:
            user_request (str): The primary topic or prompt from the user.
            context (str, optional): Additional contextual details. Defaults to None.
            
        Returns:
            str: A single, generated greeting message.
        """
        system_prompt = (
            "You are the Smart Wish Message Generator. Your goal is to create "
            "heartfelt, creative, and personalized greeting card messages. "
            "Keep messages concise but warm."
        )

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_request},
        ]

        if context:
            messages[1]["content"] += f"\nAdditional Context: {context}"

        response = self._run_inference(messages, max_tokens=300, temp=0.7, top_p=0.95, add_gen_prompt=True)
        return response.strip()

    @modal.method()
    def generate_message(self, user_request: str, context: str = None) -> str:
        """Exposed RPC method for standard message generation.
        
        This method acts as the remote entry point for generating single messages,
        allowing other services or CLI tools to invoke inference securely.
        
        Args:
            user_request (str): The primary topic or prompt.
            context (str, optional): Additional context. Defaults to None.
            
        Returns:
            str: The generated message.
        """
        return self._generate_message(user_request, context)

    def _parse_variations_json(self, response: str) -> dict:
        """Extracts and normalizes a JSON payload from the raw LLM response.
        
        Scans the response string for the first '{' and last '}' to safely 
        extract the JSON block, avoiding trailing conversational text. It maps 
        the keys to a stable schema and applies markdown stripping.
        
        Args:
            response (str): The raw string output from the LLM.
            
        Returns:
            dict: A dictionary containing 'Professional', 'casual', and 'loving' keys.
                  If parsing fails, returns a fallback error dictionary.
        """
        try:
            start_idx = response.find('{')
            end_idx = response.rfind('}')
            
            if start_idx != -1 and end_idx != -1 and end_idx >= start_idx:
                clean_json_str = response[start_idx:end_idx+1]
                data = json.loads(clean_json_str)
                
                return {
                    "Professional": self._strip_markdown(str(data.get("Professional", ""))),
                    "casual": self._strip_markdown(str(data.get("casual", data.get("Casual", "")))),
                    "loving": self._strip_markdown(str(data.get("loving", data.get("Loving", ""))))
                }
            
            raise ValueError("Incomplete or malformed JSON payload.")
        except Exception as e:
            print(f"❌ Structural Validation Error: {e}")
            return {
                "Professional": "Error generating professional version",
                "casual": "Error generating casual version",
                "loving": "Error generating loving version",
                "debug_error": str(e),
                "raw_response": response
            }

    @modal.method()
    def sanitize_input(self, raw_input: str) -> str:
        """Preprocesses raw text input into a clean, descriptive prompt.
        
        This mitigates prompt injection or overly complex inputs by rewriting 
        them into a standardized format. A low temperature is used to ensure 
        the rewrite is deterministic and faithful to the original intent.
        
        Args:
            raw_input (str): The unvalidated input from the user.
            
        Returns:
            str: The sanitized and cleanly formatted prompt.
        """
        messages = [
            {"role": "system", "content": SANITIZATION_SYSTEM_PROMPT},
            {"role": "user", "content": raw_input},
        ]

        response = self._run_inference(messages, max_tokens=200, temp=0.3, top_p=0.9, add_gen_prompt=True)
        return self._strip_markdown(response.strip())

    @modal.method()
    def sanitize_image_input(self, raw_input: str) -> str:
        """Preprocesses raw user input into a descriptive visual prompt.
        
        Translates a simple textual idea into a rich, detailed visual description 
        optimized for image generation models like Flux.
        
        Args:
            raw_input (str): The basic idea or subject for an image.
            
        Returns:
            str: A detailed prompt describing the visual scene.
        """
        messages = [
            {"role": "system", "content": IMAGE_SANITIZATION_SYSTEM_PROMPT},
            {"role": "user", "content": raw_input},
        ]

        response = self._run_inference(messages, max_tokens=200, temp=0.3, top_p=0.9, add_gen_prompt=True)
        return self._strip_markdown(response.strip())

    @modal.method()
    def generate_variations(self, user_request: str) -> dict:
        """Performs structured generation of three distinct card tones.
        
        This method uses a pre-filling technique, forcing the assistant's 
        first output token to be '{', which anchors the model into generating 
        a valid JSON structure according to the provided system schema.
        
        Args:
            user_request (str): The base topic for the greeting variations.
            
        Returns:
            dict: A normalized dictionary of variations ('Professional', 'casual', 'loving').
        """
        # Implementation note: We pre-fill the assistant response with '{'
        # to 'anchor' the model into a JSON-first generation state.
        messages = [
            {"role": "system", "content": MESSAGE_VARIATION_PROMPT},
            {"role": "user", "content": f"Input: {user_request}\n\n{RESTRICTION_ANCHOR}"},
            {"role": "assistant", "content": "{"},
        ]

        response_text = self._run_inference(messages, max_tokens=500, temp=0.7, top_p=0.95, add_gen_prompt=False)
        response_text = "{" + response_text.strip()
        return self._parse_variations_json(response_text)

    @modal.fastapi_endpoint(method="POST")
    def web_generate(self, request: dict):
        """Public FastAPI gateway for web clients.
        
        Decouples internal RPC logic from HTTP requirements, allowing the 
        Node.js orchestrator to interact via standard POST requests. It routes 
        the request to the appropriate method (sanitization, single, or variations) 
        based on the provided payload parameters.
        
        Args:
            request (dict): The parsed JSON payload from the HTTP request.
            
        Returns:
            dict: The response payload (either a generated message, sanitized prompt, 
                  or JSON variations) or an HTTP 400 error if invalid.
        """
        prompt = request.get("prompt")
        context = request.get("context")
        variations = request.get("variations", False)
        sanitize = request.get("sanitize", False)
        sanitize_image = request.get("sanitize_image", False)
        
        if not prompt:
            return {"error": "Prompt parameter is required."}, 400
            
        if sanitize:
            cleaned = self.sanitize_input.local(raw_input=prompt)
            return {"sanitized_prompt": cleaned}

        if sanitize_image:
            cleaned = self.sanitize_image_input.local(raw_input=prompt)
            return {"sanitized_prompt": cleaned}
            
        if variations:
            return self.generate_variations.local(user_request=prompt)
            
        message = self._generate_message(prompt, context)
        return {"message": self._strip_markdown(message)}
